language: java

jdk:
  - oraclejdk8

# Run on container-based infrastructure
sudo: false

cache:
  directories:
    - ${HOME}/.m2/repository

before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi

install:
  - mvn --settings .travis/settings.xml --show-version dependency:resolve
  - mvn --settings .travis/settings.xml --show-version dependency:resolve-plugins

script:
  - mvn --batch-mode --settings .travis/settings.xml --show-version test

deploy:
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: spals/midas
      branch: master
      jdk: oraclejdk8
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: spals/midas
      tags: true
      jdk: oraclejdk8
